const FranchisorAccountsSQL = 
`
INSERT INTO FranchiseOwner VALUES ('BuntinAlimentaccount','Buntin Aliment');
INSERT INTO FranchiseOwner VALUES ('JericaMealsaccount','Jerica Meals');
INSERT INTO FranchiseOwner VALUES ('JenaFoodstuffsaccount','Jena Foodstuffs');
INSERT INTO FranchiseOwner VALUES ('PawlakSustenanceaccount','Pawlak Sustenance');
INSERT INTO FranchiseOwner VALUES ('TestaniVittlesaccount','Testani Vittles');
INSERT INTO FranchiseOwner VALUES ('TheodoreMealsaccount','Theodore Meals');
INSERT INTO FranchiseOwner VALUES ('WitterAlimentaccount','Witter Aliment');
INSERT INTO FranchiseOwner VALUES ('MaustDietaccount','Maust Diet');
INSERT INTO FranchiseOwner VALUES ('VilleneuveViandsaccount','Villeneuve Viands');
INSERT INTO FranchiseOwner VALUES ('HerzTableaccount','Herz Table');
INSERT INTO FranchiseOwner VALUES ('FethFareaccount','Feth Fare');
INSERT INTO FranchiseOwner VALUES ('HalLarderaccount','Hal Larder');
INSERT INTO FranchiseOwner VALUES ('JefferyVittlesaccount','Jeffery Vittles');
INSERT INTO FranchiseOwner VALUES ('KristanHaute-cuisineaccount','Kristan Haute-cuisine');
INSERT INTO FranchiseOwner VALUES ('ArpinDietaccount','Arpin Diet');
INSERT INTO FranchiseOwner VALUES ('MyriamCookingaccount','Myriam Cooking');
INSERT INTO FranchiseOwner VALUES ('DenishaSoul-foodaccount','Denisha Soul-food');
INSERT INTO FranchiseOwner VALUES ('CarlotaNutrimentaccount','Carlota Nutriment');
INSERT INTO FranchiseOwner VALUES ('PeterNourishmentaccount','Peter Nourishment');
INSERT INTO FranchiseOwner VALUES ('PressFast-foodaccount','Press Fast-food');
INSERT INTO FranchiseOwner VALUES ('MicaelaEdiblesaccount','Micaela Edibles');
INSERT INTO FranchiseOwner VALUES ('KatharynMessaccount','Katharyn Mess');
INSERT INTO FranchiseOwner VALUES ('JefferyMealsaccount','Jeffery Meals');
INSERT INTO FranchiseOwner VALUES ('JefferyFoodstuffsaccount','Jeffery Foodstuffs');
INSERT INTO FranchiseOwner VALUES ('MimiBreadaccount','Mimi Bread');
INSERT INTO FranchiseOwner VALUES ('HolleyMeat and drinkaccount','Holley Meat and drink');
INSERT INTO FranchiseOwner VALUES ('MohammedDietaccount','Mohammed Diet');
INSERT INTO FranchiseOwner VALUES ('WisneskiFareaccount','Wisneski Fare');
INSERT INTO FranchiseOwner VALUES ('DebbyFast-foodaccount','Debby Fast-food');
INSERT INTO FranchiseOwner VALUES ('CarmineStoresaccount','Carmine Stores');
INSERT INTO FranchiseOwner VALUES ('MohammedHaute-cuisineaccount','Mohammed Haute-cuisine');
INSERT INTO FranchiseOwner VALUES ('PeterSubsistenceaccount','Peter Subsistence');
INSERT INTO FranchiseOwner VALUES ('TavaresSubsistenceaccount','Tavares Subsistence');
INSERT INTO FranchiseOwner VALUES ('MathiesonSoul-foodaccount','Mathieson Soul-food');
INSERT INTO FranchiseOwner VALUES ('SiebertRationsaccount','Siebert Rations');
INSERT INTO FranchiseOwner VALUES ('IveyFast-foodaccount','Ivey Fast-food');
INSERT INTO FranchiseOwner VALUES ('SiebertVictualsaccount','Siebert Victuals');
INSERT INTO FranchiseOwner VALUES ('KatharynFareaccount','Katharyn Fare');
INSERT INTO FranchiseOwner VALUES ('JacalynHaute-cuisineaccount','Jacalyn Haute-cuisine');
INSERT INTO FranchiseOwner VALUES ('ChaffinsMenuaccount','Chaffins Menu');
INSERT INTO FranchiseOwner VALUES ('DennRationsaccount','Denn Rations');
INSERT INTO FranchiseOwner VALUES ('JefferyComfort-foodaccount','Jeffery Comfort-food');
INSERT INTO FranchiseOwner VALUES ('MohammedPabulumaccount','Mohammed Pabulum');
INSERT INTO FranchiseOwner VALUES ('PechacekEdiblesaccount','Pechacek Edibles');
INSERT INTO FranchiseOwner VALUES ('PressTableaccount','Press Table');
INSERT INTO FranchiseOwner VALUES ('RoxieMessaccount','Roxie Mess');
INSERT INTO FranchiseOwner VALUES ('AdahNutrimentaccount','Adah Nutriment');
INSERT INTO FranchiseOwner VALUES ('MohammedCookeryaccount','Mohammed Cookery');
INSERT INTO FranchiseOwner VALUES ('MicaelaMealsaccount','Micaela Meals');
INSERT INTO FranchiseOwner VALUES ('PressProvisionsaccount','Press Provisions');
`
function getFranchisorAccountsSQL() { return FranchisorAccountsSQL ;}
module.exports = getFranchisorAccountsSQL;